import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Netflix Clone</title>
        <meta name='description' content='Generated by create Netflix Clone' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <div>Boy boing boing</div>
      </main>
    </>
  )
}
